version: "3"
services:
  jupyter:
    # From the jupyter minimal notebook image
    image: jupyter/minimal-notebook
    # Map the host port (8888) to the container port (8888)
    ports:
      - "8888:8888"
    # Set the token to the environment variable defined in .env
    environment:
        JUPYTER_TOKEN: "$JUPYTER_TOKEN"
    # Map (in ABSOLUTE) the host folder path to the Jupyter Container Work Directory
    volumes:
       - /Users/paulogier/87-docker_parent/usingjupyterwithdocker/Step2_SimpleDockerCompose/Jupyter_Home_Folder:/home/jovyan/
