version: "3"
services:
  jupyter_service:
    # From the Dockerfile for jupyter defined in /Dockerfiles/dockerfile-jupyter
    # Give a name to this image
    build:
      context: ./
      dockerfile: ./Dockerfiles/dockerfile-jupyter
    image: ogierpaul/jupsy

    # Map the host port (8888) to the container port (8888)
    ports:
      - "8888:8888"
    # Set the token to the environment variable defined in .env
    environment:
        JUPYTER_TOKEN: "$JUPYTER_TOKEN"
        POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
    # Map (in ABSOLUTE) the host folder path to the Jupyter Container Work Directory
    volumes:
       - /Users/paulogier/87-docker_parent/usingjupyterwithdocker/Step6_ConnectingPostgres/Jupyter_Home_Folder:/home/jovyan/
    #
    links:
      - postgres_service

  postgres_service:
    # Use the official image from PostgreSQL
    image: postgres
    # Set up some environment variables. Password is stored in the .env file
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: mydb
