version: "3"
services:
  jupyter_service:
    build:
      context: ./
      dockerfile: ./dockerfile-jupyter
    # Map the host port (8888) to the container port (8888)
    ports:
      - "8888:8888"
    # Set the token to the environment variable defined in .env
    environment:
        GRANT_SUDO: 'yes'
        CHOWN_HOME: 'yes'
        CHOWN_HOME_OPTS: '-R'
        JUPYTER_TOKEN: "$JUPYTER_TOKEN"
        POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
    # Map (in ABSOLUTE) the host folder path to the Jupyter Container Work Directory
    volumes:
      - type: bind
        source: /Users/paulogier/87-docker_parent/usingjupyterwithdocker/Step8_Final/work
        target: /home/jovyan/work
      - type: bind
        source: /Users/paulogier/87-docker_parent/usingjupyterwithdocker/Step8_Final/stagingarea
        target: /home/jovyan/stagingarea

  postgres_service:
    # Use the official image from PostgreSQL
    image: postgres
    # Set up some environment variables. Password is stored in the .env file
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: mydb
    volumes:
      - type: bind
        source: /Users/paulogier/87-docker_parent/usingjupyterwithdocker/Step8_Final/stagingarea
        target: /home/stagingarea
